version: '3'
services:
  ghost:
    image: ghost:latest
    restart: always
    depends_on:
      - db
    environment:
      url: http://${SERVER_URL:?err}
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASS:?err}
      database__connection__database: ghost
      logging__path: /logs
      logging__info: 'info'
      mail__transport: 'SMTP'
      mail__from: '${GMAIL_EMAIL:?err}'
      mail__options__service: 'gmail'
      mail__options__host: 'smtp.gmail.com'
      mail__options__port: 465
      mail__options__secure: 'true'
      mail__options__auth__user: '${GMAIL_EMAIL:?err}'
      mail__options__auth__pass: '${GMAIL_PASS:?err}'
    volumes:
      - ./ghost_content:/var/lib/ghost/content
      - ./ghost_logs:/logs

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS:?err}
    volumes:
      - ./ghost_mysql:/var/lib/mysql

  nginx:
    image: staticfloat/nginx-certbot
    restart: unless-stopped
    depends_on:
      - ghost
    ports:
      - '80:80'
      - '443:443'
    environment:
      CERTBOT_EMAIL: till.gartner@gmail.com
      SERVER_URL: ${SERVER_URL:?err}
      ENVSUBST_VARS: SERVER_URL
    volumes:
      #- ./nginx_html:/usr/share/nginx/html:ro
      - ./nginx_conf:/etc/nginx
      - ./nginx_logs:/logs
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/logs:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
