version: '3'
services:
  ghost:
    image: ghost:4.11-alpine
    container_name: ghost
    restart: unless-stopped
    networks:
      - ghost_network
    depends_on:
      - db
    environment:
      url: http://{{ server_url }}
      database__client: mysql
      database__connection__host: db
      database__connection__user: {{ db_user }}
      database__connection__password: {{ db_pass }}
      database__connection__database: {{ db_database }}
      logging__path: /logs
      logging__info: 'info'
      mail__transport: 'SMTP'
      mail__from: {{ gmail_email }}
      mail__options__service: 'gmail'
      mail__options__host: 'smtp.gmail.com'
      mail__options__port: 465
      mail__options__secure: 'true'
      mail__options__auth__user: {{ gmail_email }}
      mail__options__auth__pass: {{ gmail_email }}
    volumes:
      - ./ghost_content:/var/lib/ghost/content
      - ./ghost_logs:/logs

  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: unless-stopped
    cap_add:
      - SYS_NICE # Neede b/o a MySQL-Bug
    networks:
      - ghost_network
    environment:
      MYSQL_ROOT_PASSWORD: {{ db_root_pass }}
      MYSQL_DATABASE: {{ db_database }}
    volumes:
      - ./ghost_mysql/data:/var/lib/mysql
      - ./ghost_mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d 

  nginx:
    image: jonasal/nginx-certbot:2.4.0-alpine
    #image: nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - ghost_network
    depends_on:
      - ghost
    ports:
      - '80:80'
      - '443:443'
    environment:
      CERTBOT_EMAIL: {{ certbot_email }}
      SERVER_URL: {{ server_url }}
      USE_LOCAL_CA: {{ certbot_use_local_ca }}
      DEBUG: {{ certbot_debug }}
    volumes:
      - ./nginx_html:/usr/share/nginx/html:ro
      - ./nginx_logs:/logs
      - ./nginx_secrets:/etc/letsencrypt
      - ./nginx_conf.d:/etc/nginx/user_conf.d

networks:
  ghost_network:
    name: ghost_network
